# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
    {
        :name => "hadoop-master",
        :box  => "ubuntu/trusty64",
        :eth1 => "192.168.5.10",
        :mem  => "1024",
        :cpu  => "2",
        :files => [
            { :src => "files/lists/",     :dst => "/home/vagrant/" },
            { :src => "files/archives/",  :dst => "/home/vagrant/" },
            { :src => "files/hadoop/",    :dst => "/home/vagrant/" },
            { :src => "files/resources/", :dst => "/home/vagrant/" },
            { :src => "files/system/",    :dst => "/home/vagrant/" }
        ],
        :shells => [
            "shells/start.sh",
            "shells/aptupdate.sh",
            "shells/apt.sh",
            "shells/gethadoop.sh",
            "shells/ssh.sh",
            "shells/generic.sh",
            "shells/done.sh"
        ],
        :ports_forward => [
        ]
    }
]

Vagrant.configure(2) do |config|
    boxes.each do |opts|

        config.vm.define opts[:name] do |config|
            config.vbguest.auto_update = false
            config.vbguest.no_remote = true

            config.vm.provider "virtualbox" do |v, override|
                override.vm.box = opts[:box]
            end

            config.vm.hostname = opts[:name]
  
            config.vm.provider "virtualbox" do |v|
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
            end

            config.vm.network :private_network, ip: opts[:eth1]

            opts[:ports_forward].each do |item|
                config.vm.network "forwarded_port", guest: item[:guest], host: item[:host]
            end

            opts[:files].each do |fileitem|
                config.vm.provision :file do |file|
                    file.source = fileitem[:src]
                    file.destination = fileitem[:dst]
                end
            end

            opts[:shells].each do |item|
                config.vm.provision :shell, path: item
            end
        end
    end
end
