# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
    {
        :name => "hadoop-master",
        :box  => "ubuntu/trusty64",
        :eth1 => "192.168.5.10",
        :mem  => "1536",
        :cpu  => "2",
        :files => [
            { :src => "files/lists/",     :dst => "/home/vagrant/" },
            { :src => "files/archives/",  :dst => "/home/vagrant/" },
            { :src => "files/hadoop/",    :dst => "/home/vagrant/" },
            { :src => "files/resources/", :dst => "/home/vagrant/" },
            { :src => "files/system/",    :dst => "/home/vagrant/" },
        ],
        :shells => [
            "shells/aptupdate.sh",
            "shells/apt.sh",
            "shells/generic.sh",
            "shells/ssh.sh",
            "shells/gethadoop.sh",
            "shells/monitoring.sh",
            "shells/done.sh",
        ],
        :ports_forward => [
            { :guest => "54310", :host => "54310" }, # fs.defaultFS
            { :guest => "54311", :host => "54311" }, # mapreduce.jobtracker.address
            { :guest => "8030",  :host => "8030"  }, # yarn.resourcemanager.scheduler.address
            { :guest => "8032",  :host => "8032"  }, # yarn.resourcemanager.address
            { :guest => "8088",  :host => "8088"  }, # yarn.resourcemanager.webapp.address
            { :guest => "8031",  :host => "8031"  }, # yarn.resourcemanager.resource-tracker.address
            { :guest => "8033",  :host => "8033"  }, # yarn.resourcemanager.admin.address
            { :guest => "50070", :host => "50070" }, # dfs.namenode.http-address
            { :guest => "3000",  :host => "3000"  }, # grafana
            { :guest => "9000",  :host => "9000"  }, # password entropy app
        ]
    },
    {
        :name => "hadoop-slave1",
        :box  => "ubuntu/trusty64",
        :eth1 => "192.168.5.11",
        :mem  => "1536",
        :cpu  => "2",
        :files => [
            { :src => "files/lists/",     :dst => "/home/vagrant/" },
            { :src => "files/archives/",  :dst => "/home/vagrant/" },
            { :src => "files/hadoop/",    :dst => "/home/vagrant/" },
            { :src => "files/resources/", :dst => "/home/vagrant/" },
            { :src => "files/system/",    :dst => "/home/vagrant/" },
        ],
        :shells => [
            "shells/aptupdate.sh",
            "shells/apt.sh",
            "shells/generic.sh",
            "shells/ssh.sh",
            "shells/gethadoop.sh",
            "shells/monitoring.sh",
            "shells/done.sh",
        ],
        :ports_forward => [
        ]
    },
    {
        :name => "hadoop-slave2",
        :box  => "ubuntu/trusty64",
        :eth1 => "192.168.5.12",
        :mem  => "1536",
        :cpu  => "2",
        :files => [
            { :src => "files/lists/",     :dst => "/home/vagrant/" },
            { :src => "files/archives/",  :dst => "/home/vagrant/" },
            { :src => "files/hadoop/",    :dst => "/home/vagrant/" },
            { :src => "files/resources/", :dst => "/home/vagrant/" },
            { :src => "files/system/",    :dst => "/home/vagrant/" },
        ],
        :shells => [
            "shells/aptupdate.sh",
            "shells/apt.sh",
            "shells/generic.sh",
            "shells/ssh.sh",
            "shells/gethadoop.sh",
            "shells/monitoring.sh",
            "shells/done.sh",
        ],
        :ports_forward => [
        ]
    }
]

Vagrant.configure(2) do |config|
    boxes.each do |opts|

        config.vm.define opts[:name] do |config|
            config.vm.boot_timeout = 600
            config.vbguest.auto_update = false
            config.vbguest.no_remote = true
            config.ssh.insert_key = false

            config.vm.provider "virtualbox" do |v, override|
                override.vm.box = opts[:box]
            end

            config.vm.hostname = opts[:name]

            config.vm.provider "virtualbox" do |v|
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
            end

            config.vm.network :private_network, ip: opts[:eth1]

            opts[:ports_forward].each do |item|
                config.vm.network "forwarded_port", guest: item[:guest], host: item[:host], host_ip: "127.0.0.1"
            end

            opts[:files].each do |fileitem|
                config.vm.provision :file do |file|
                    file.source = fileitem[:src]
                    file.destination = fileitem[:dst]
                end
            end

            opts[:shells].each do |item|
                config.vm.provision :shell, path: item
            end
        end
    end
end
